/**
 * mSupply Mobile
 * Sustainable Solutions (NZ) Ltd. 2019
 */

export const PREFERENCE_KEYS = {
  CONSUMPTION_LOOKBACK_PERIOD: 'monthlyConsumptionLookBackPeriod',
  CONSUMPTION_ENFORCE_LOOKBACK: 'monthlyConsumptionEnforceLookBackPeriod',
  MONTHS_LEAD_TIME: 'monthsLeadTime',
  VACCINE_MODULE: 'usesVaccineModule',
  DISPENSARY_MODULE: 'usesDispensaryModule',
  DASHBOARD_MODULE: 'usesDashboardModule',
  CASH_REGISTER_MODULE: 'usesCashRegisterModule',
  PAYMENT_MODULE: 'usesPaymentModule',
  PATIENT_TYPES: 'usesPatientTypes',
  HIDE_SNAPSHOT_COLUMN: 'usesHideSnapshotColumn',
  CAN_EDIT_PATIENTS_FROM_ANY_STORE: 'can_edit_patients_from_any_store',
};

export const PREFERENCE_TYPE_KEYS = {
  NUMERIC: 'numeric',
  NON_NEGATIVE_NUMERIC: 'non_negative_numeric',
  BOOL: 'bool',
};

export const PREFERENCE_TYPES = {
  [PREFERENCE_KEYS.CONSUMPTION_LOOKBACK_PERIOD]: PREFERENCE_TYPE_KEYS.NON_NEGATIVE_NUMERIC,
  [PREFERENCE_KEYS.CONSUMPTION_ENFORCE_LOOKBACK]: PREFERENCE_TYPE_KEYS.BOOL,
  [PREFERENCE_KEYS.MONTHS_LEAD_TIME]: PREFERENCE_TYPE_KEYS.NON_NEGATIVE_NUMERIC,
  [PREFERENCE_KEYS.VACCINE_MODULE]: PREFERENCE_TYPE_KEYS.BOOL,
  [PREFERENCE_KEYS.DISPENSARY_MODULE]: PREFERENCE_TYPE_KEYS.BOOL,
  [PREFERENCE_KEYS.DASHBOARD_MODULE]: PREFERENCE_TYPE_KEYS.BOOL,
  [PREFERENCE_KEYS.CASH_REGISTER_MODULE]: PREFERENCE_TYPE_KEYS.BOOL,
  [PREFERENCE_KEYS.PAYMENT_MODULE]: PREFERENCE_TYPE_KEYS.BOOL,
  [PREFERENCE_KEYS.PATIENT_TYPES]: PREFERENCE_TYPE_KEYS.BOOL,
  [PREFERENCE_KEYS.HIDE_SNAPSHOT_COLUMN]: PREFERENCE_TYPE_KEYS.BOOL,
  [PREFERENCE_KEYS.CAN_EDIT_PATIENTS_FROM_ANY_STORE]: PREFERENCE_TYPE_KEYS.BOOL,
};
