/**
 * mSupply Mobile
 * Sustainable Solutions (NZ) Ltd. 2019
 */

export const COLUMN_TYPES = {
  CHECKABLE: 'checkable',
  CURRENCY: 'currency',
  EDITABLE_EXPIRY_DATE: 'editableExpiryDate',
  DATE: 'date',
  DROP_DOWN: 'dropdown',
  ICON: 'icon',
  EDITABLE_NUMERIC: 'editableNumeric',
  NUMERIC: 'numeric',
  EDITABLE_STRING: 'editableString',
  STRING: 'string',
};

export const COLUMN_KEYS = {
  AVAILABLE_QUANTITY: 'availableQuantity',
  BATCH: 'batch',
  CODE: 'code',
  COMMENT: 'comment',
  CONFIRM_DATE: 'confirmDate',
  COST_PRICE: 'costPriceString',
  COUNTED_TOTAL_QUANTITY: 'countedTotalQuantity',
  CREATED_DATE: 'createdDate',
  DATE_OF_BIRTH: 'dateOfBirth',
  DIFFERENCE: 'difference',
  DISPENSE: 'dispense',
  ENTRY_DATE: 'entryDate',
  EXPIRY_DATE: 'expiryDate',
  FIRST_NAME: 'firstName',
  ITEM_CODE: 'itemCode',
  ITEM_NAME: 'itemName',
  LAST_NAME: 'lastName',
  MONTHLY_USAGE: 'monthlyUsage',
  NAME: 'name',
  NUMBER_OF_ITEMS: 'numberOfItems',
  NUMBER_OF_PACKS: 'numberOfPacks',
  OTHER_PARTY_NAME: 'otherPartyName',
  OUR_STOCK_ON_HAND: 'ourStockOnHand',
  PATIENT_EDIT: 'patientEdit',
  PATIENT_HISTORY: 'patientHistory',
  PRESCRIBER_EDIT: 'prescriberEdit',
  PRESCRIBER: 'prescriber',
  PRICE: 'price',
  REASON_TITLE: 'reasonTitle',
  REGISTRATION_CODE: 'registrationCode',
  REMOVE: 'remove',
  REQUIRED_QUANTITY: 'requiredQuantity',
  RETURN_AMOUNT: 'returnAmount',
  RETURN: 'return',
  SELECT: 'select',
  SELECTED: 'selected',
  SELL_PRICE: 'sellPriceString',
  SERIAL_NUMBER: 'serialNumber',
  SNAPSHOT_TOTAL_QUANTITY: 'snapshotTotalQuantity',
  STATUS: 'status',
  STOCK_ON_HAND: 'stockOnHand',
  SUGGESTED_QUANTITY: 'suggestedQuantity',
  SUPPLIED_QUANTITY: 'suppliedQuantity',
  TOTAL: 'total',
  TOTAL_QUANTITY: 'totalQuantity',
  TYPE: 'type',
  UNIT: 'unitString',
  VALUE: 'value',
};

export const COLUMN_NAMES = {
  AVAILABLE_QUANTITY: 'availableQuantity',
  BATCH_NAME: 'batch',
  BATCHES: 'batches',
  CASH_REASON: 'cashReason',
  CODE: 'code',
  COMMENT: 'comment',
  CONFIRM_DATE: 'confirmDate',
  COST_PRICE: 'costPrice',
  COUNTED_TOTAL_QUANTITY: 'countedTotalQuantity',
  CREATED_DATE: 'createdDate',
  CUSTOMER: 'customer',
  DATE_OF_BIRTH: 'dateOfBirth',
  DIFFERENCE: 'difference',
  DISPENSE: 'dispense',
  EDITABLE_BATCH_NAME: 'editableBatchName',
  EDITABLE_COMMENT: 'editableComment',
  EDITABLE_EXPIRY_DATE: 'editableExpiryDate',
  EDITABLE_REQUIRED_QUANTITY: 'editableRequiredQuantity',
  EDITABLE_TOTAL_QUANTITY: 'editableTotalQuantity',
  EDITABLE_VALUE: 'editableValue',
  ENTRY_DATE: 'entryDate',
  FIRST_NAME: 'firstName',
  INVOICE_NUMBER: 'invoiceNumber',
  ITEM_CODE: 'itemCode',
  ITEM_NAME: 'itemName',
  LAST_NAME: 'lastName',
  MONTHLY_USAGE: 'monthlyUsage',
  NAME: 'name',
  NUMBER_OF_ITEMS: 'numberOfItems',
  NUMBER_OF_PACKS: 'numberOfPacks',
  OTHER_PARTY_NAME: 'otherPartyName',
  OUR_STOCK_ON_HAND: 'ourStockOnHand',
  PATIENT_EDIT: 'patientEdit',
  PATIENT_HISTORY: 'patientHistory',
  PAYMENT_NAME: 'paymentName',
  PRESCRIBER_EDIT: 'prescriberEdit',
  PRESCRIBER: 'prescriber',
  PRICE: 'price',
  QUESTION: 'question',
  REASON: 'reason',
  REGISTRATION_CODE: 'registrationCode',
  REMOVE: 'remove',
  REQUIRED_QUANTITY: 'requiredQuantity',
  REQUISITION_NUMBER: 'requisitionNumber',
  RETURN_AMOUNT: 'returnAmount',
  RETURN: 'return',
  SELECT: 'select',
  SELECTED: 'selected',
  SELL_PRICE: 'sellPrice',
  SNAPSHOT_TOTAL_QUANTITY: 'snapshotTotalQuantity',
  STATUS: 'status',
  SUGGESTED_QUANTITY: 'suggestedQuantity',
  SUPPLIED_QUANTITY: 'suppliedQuantity',
  SUPPLIER: 'supplier',
  THEIR_STOCK_ON_HAND: 'theirStockOnHand',
  TOTAL: 'total',
  TOTAL_QUANTITY: 'totalQuantity',
  TRANSACT_TYPE: 'transactType',
  UNIT: 'unit',
  EDIT_SUPPLIER: 'editSupplier',
};

export default { COLUMN_TYPES, COLUMN_NAMES, COLUMN_KEYS };
