// @ts-check

export const COLUMN_TYPES = {
  CHECKABLE: 'checkable',
  DATE_EDITABLE: 'editableDate',
  DATE: 'date',
  DROP_DOWN: 'dropdown',
  ICON: 'icon',
  NUMERIC_EDITABLE: 'editableNumeric',
  NUMERIC: 'numeric',
  STRING_EDITABLE: 'editableString',
  STRING: 'string',
};

export const COLUMN_KEYS = {
  AVAILABLE_QUANTITY: 'availableQuantity',
  BATCHES: 'batches',
  BATCH: 'batch',
  BATCH_NAME: 'batch',
  CODE: 'code',
  COMMENT: 'comment',
  COUNTED_TOTAL_QUANTITY: 'countedTotalQuantity',
  CREATED_DATE: 'createdDate',
  CUSTOMER: 'customer',
  DIFFERENCE: 'difference',
  ENTRY_DATE: 'entryDate',
  EDITABLE_COMMENT: 'editableComment',
  EDITABLE_VALUE: 'editableValue',
  EDITABLE_REQUIRED_QUANTITY: 'editableRequiredQuantity',
  EXPIRY_DATE: 'expiryDate',
  ITEM_CODE: 'itemCode',
  ITEM_NAME: 'itemName',
  INVOICE_NUMBER: 'invoiceNumber',
  MONTHLY_USAGE: 'monthlyUsage',
  NAME: 'name',
  NUMBER_OF_ITEMS: 'numberOfItems',
  OTHER_PARTY_NAME: 'otherPartyName',
  OUR_STOCK_ON_HAND: 'ourStockOnHand',
  THEIR_STOCK_ON_HAND: 'theirStockOnHand',
  PRICE: 'price',
  REASON: 'reason',
  REASON_TITLE: 'reasonTitle',
  QUESTION: 'question',
  REMOVE: 'remove',
  REQUIRED_QUANTITY: 'requiredQuantity',
  REQUISITION_NUMBER: 'requisitionNumber',
  SELECTED: 'selected',
  SERIAL_NUMBER: 'serialNumber',
  SNAPSHOT_TOTAL_QUANTITY: 'snapshotTotalQuantity',
  STATUS: 'status',
  STOCK_ON_HAND: 'stockOnHand',
  SUGGESTED_QUANTITY: 'suggestedQuantity',
  SUPPLIED_QUANTITY: 'suppliedQuantity',
  SUPPLIER: 'supplier',
  TOTAL_QUANTITY: 'totalQuantity',
  UNIT: 'unit',
  VALUE: 'value',
};

export default { COLUMN_TYPES, COLUMN_KEYS };
