/* @flow weak */

/**
 * mSupply Mobile
 * Sustainable Solutions (NZ) Ltd. 2016
 */

import LocalizedStrings from 'react-native-localization';

export const modalStrings = new LocalizedStrings({
  gb: {
    add_at_least_one_item_before_finalising: 'You need to add at least one item before finalising',
    and: 'and',
    cancel: 'Cancel',
    confirm: 'Confirm',
    create: 'Create',
    delete_these_invoices: 'Are you sure you want to delete these invoices?',
    delete_these_requisitions: 'Are you sure you want to delete these requisitions?',
    delete_these_stocktakes: 'Are you sure you want to delete these stocktakes?',
    delete: 'Delete',
    edit_the_invoice_comment: 'Edit the invoice comment',
    edit_the_requisition_comment: 'Edit the requisition comment',
    edit_their_reference: 'Edit their reference',
    finalise_customer_invoice: 'Finalise will lock this invoice permanently.',
    finalise_requisition: 'Finalise will send this requisition and lock it permanently.',
    finalise_stocktake: 'Finalise will adjust inventory and lock this stocktake permanently.',
    finalise_supplier_invoice: 'Finalise will adjust inventory and lock this invoice permanently.',
    following_items_reduced_more_than_available_stock: 'The following items have been reduced by more than the available stock:',
    give_your_stocktake_a_name: 'Give your stocktake a name',
    got_it: 'Got it',
    more: 'more',
    record_stock_required_before_finalising: 'You need to record how much stock is required before finalising',
    record_stock_to_issue_before_finalising: 'You need to record how much stock to issue before finalising',
    remove_these_items: 'Are you sure you want to remove these items?',
    remove: 'Remove',
    search_for_an_item_to_add: 'Search for an item to add',
    search_for_the_customer: 'Search for the customer',
    select_a_language: 'Select a language',
    select_the_number_of_months_stock_required: 'Select the number of months stock required',
    start_typing_to_select_customer: 'Start typing to select customer',
    stocktake_no_counted_items: "Can't finalise a stocktake with no counted items",
  },
  tl: {
    add_at_least_one_item_before_finalising: 'Tenke hatama sasán ida antes finaliza',
    and: 'no',
    cancel: 'Kansela',
    confirm: 'Konfirma',
    create: 'Kria',
    delete_these_invoices: "Ita sente tebes ita hakarak hapus konta sira-ne'e?",
    delete_these_requisitions: "Ita sente tebes ita hakarak hapus rekuizisaun sira-ne'e?",
    delete_these_stocktakes: "Ita sente tebes ita hakarak hapus ajustamentu sira-ne'e?",
    delete: 'Hapus',
    edit_the_invoice_comment: 'Hadia komentáriu iha konta',
    edit_the_requisition_comment: 'Hadia komentáriu iha rekuizisaun',
    edit_their_reference: 'Hadia sira-nia referensia',
    finalise_customer_invoice: "Finaliza sei xave permanente konta ne'e.",
    finalise_requisition: "Finaliza sei hamenu rekuizisaun ne'e no xave permanente.",
    finalise_stocktake: "Finaliza sei ajusta inventariu no xave permanente ajustamentu ne'e.",
    finalise_supplier_invoice: "Finaliza sei ajusta inventariu no xave permanente konta ne'e.",
    following_items_reduced_more_than_available_stock: "Sasán tuirmai ne'e la bele hamenus nia kuantidade menus liu duke kuantidade sasán atuál:",
    give_your_stocktake_a_name: 'Fó naran ba ita-nia ajustamentu',
    got_it: 'Komprende',
    more: 'aumenta tan',
    record_stock_required_before_finalising: "Ita tenke hatama info kona-ba sasán hira ne'ebé presiza antes bele halo finaliza",
    record_stock_to_issue_before_finalising: "Ita tenke hatama info kona-ba sasán hira ne'ebé atu haruka antes bele halo finaliza",
    remove_these_items: "Ita tebes hakarak hasai sasán sira-ne'e?",
    remove: 'Hasai',
    search_for_an_item_to_add: 'Buka-hetan sasán atu hatama',
    search_for_the_customer: 'Buka-hetan kliente',
    select_a_language: 'Hili lingua',
    select_the_number_of_months_stock_required: 'Hili sasán fulan hira mak presiza',
    start_typing_to_select_customer: 'Komesa ketik hodi bele hili kliente',
    stocktake_no_counted_items: "La bele finalize ajustamentu se la iha sasán ne'ebé sura tiha",
  },
});
