/**
 * mSupply Mobile
 * Sustainable Solutions (NZ) Ltd. 2019
 */

import LocalizedStrings from 'react-native-localization';

export const programStrings = new LocalizedStrings({
  gb: {
    select_a_program: 'Select a program',
    select_a_supplier: 'Select a supplier',
    select_an_order_type: 'Select an order type',
    select_a_period: 'Select a period',
    no_programs: 'No programs available',
    no_suppliers: 'No suppliers available',
    no_order_types: 'No order types available',
    no_periods: 'No periods available',
    program: 'Program',
    supplier: 'Supplier',
    order_type: 'Order type',
    period: 'Period',
    max_mos: 'Max MOS',
    threshold_mos: 'Threshold MOS',
    max_orders_per_period: 'Max orders per period',
    requisitions: 'Requisition(s)',
    details: 'Details',
    general: 'General',
    order: 'order',
    not_applicable: 'Not applicable',
    hide_over_stocked: 'Hide over stocked',
    show_over_stocked: 'Show over stocked',
    program_order: 'Program order',
    general_stocktake: 'General stocktake',
    program_stocktake: 'Program stocktake',
    general_order: 'General order',
    emergency_order: 'Emergency order',
    max_items: 'Max. Items',
  },
  fr: {
    select_a_program: 'Sélectionnez un programme',
    select_a_supplier: 'Sélectionnez un fournisseur',
    select_an_order_type: 'Sélectionnez un type de commande',
    select_a_period: 'Sélectionnez une période',
    no_programs: 'Aucun programme disponible',
    no_suppliers: 'Aucun fournisseur disponible',
    no_order_types: 'Aucun type de commande disponible',
    no_periods: 'Aucune période disponible',
    program: 'Programme\n',
    supplier: 'Fournisseur',
    order_type: 'Type de commande',
    period: 'Période',
    max_mos: 'MDS Max',
    threshold_mos: 'Seuil MDS',
    max_orders_per_period: 'Commandes max. par période',
    requisitions: 'Réquisition(s)',
    details: 'Détails',
    general: 'Général',
    order: 'commande',
    not_applicable: 'Pas applicable',
    hide_over_stocked: 'Masquer les\nproduits surstocké',
    show_over_stocked: 'Afficher les\nproduits surstocké',
    program_order: 'Commande par\nprogramme',
    general_stocktake: 'Inventaire général',
    general_order: 'Commande Générale',
    program_stocktake: 'Inventaire par\n programme',
    emergency_order: ' Commandes urgence',
  },
  gil: {
    select_a_program: 'Select a program',
    select_a_supplier: 'Select a supplier',
    select_an_order_type: 'Select an order type',
    select_a_period: 'Select a period',
    no_programs: 'No programs available',
    no_suppliers: 'No suppliers available',
    no_order_types: 'No order types available',
    no_periods: 'No periods available',
    program: 'Program',
    supplier: 'Supplier',
    order_type: 'Order type',
    period: 'Period',
    max_mos: 'Max MOS',
    threshold_mos: 'Threshold MOS',
    max_orders_per_period: 'Max orders per period',
    requisitions: 'Requisition(s)',
    details: 'Details',
    general: 'General',
    order: 'order',
    not_applicable: 'Not applicable',
    hide_over_stocked: 'Hide over stocked',
    show_over_stocked: 'Show over stocked',
    program_order: 'Program order',
    general_stocktake: 'General stocktake',
    general_order: 'General order',
    program_stocktake: 'Inventaire général',
  },
  tl: {
    select_a_program: 'Select a program',
    select_a_supplier: 'Select a supplier',
    select_an_order_type: 'Select an order type',
    select_a_period: 'Select a period',
    no_programs: 'No programs available',
    no_suppliers: 'No suppliers available',
    no_order_types: 'No order types available',
    no_periods: 'No periods available',
    program: 'Program',
    supplier: 'Supplier',
    order_type: 'Order type',
    period: 'Period',
    max_mos: 'Max MOS',
    threshold_mos: 'Threshold MOS',
    max_orders_per_period: 'Max orders per period',
    requisitions: 'Requisition(s)',
    details: 'Details',
    general: 'General',
    order: 'order',
    not_applicable: 'Not applicable',
    hide_over_stocked: 'Hide over stocked',
    show_over_stocked: 'Show over stocked',
    program_order: 'Program order',
    general_stocktake: 'General stocktake',
    general_order: 'General order',
    program_stocktake: 'Inventaire général',
  },
  la: {
    select_a_program: 'Select a program',
    select_a_supplier: 'Select a supplier',
    select_an_order_type: 'Select an order type',
    select_a_period: 'Select a period',
    no_programs: 'No programs available',
    no_suppliers: 'No suppliers available',
    no_order_types: 'No order types available',
    no_periods: 'No periods available',
    program: 'Program',
    supplier: 'Supplier',
    order_type: 'Order type',
    period: 'Period',
    max_mos: 'Max MOS',
    threshold_mos: 'Threshold MOS',
    max_orders_per_period: 'Max orders per period',
    requisitions: 'Requisition(s)',
    details: 'Details',
    general: 'General',
    order: 'order',
    not_applicable: 'Not applicable',
    hide_over_stocked: 'Hide over stocked',
    show_over_stocked: 'Show over stocked',
    program_order: 'Program order',
    general_stocktake: 'General stocktake',
    general_order: 'General order',
    program_stocktake: 'Inventaire général',
  },
});

export default programStrings;
