/**
 * mSupply Mobile
 * Sustainable Solutions (NZ) Ltd. 2019
 */

import LocalizedStrings from 'react-native-localization';

export const programStrings = new LocalizedStrings({
  gb: {
    select_a_program: 'Select a program',
    select_a_supplier: 'Select a supplier',
    select_an_order_type: 'Select an order type',
    select_a_period: 'Select a period',
    no_programs: 'No programs available',
    no_suppliers: 'No suppliers available',
    no_order_types: 'No order types available',
    no_periods: 'No periods available',
    program: 'program',
    supplier: 'supplier',
    order_type: 'order type',
    period: 'period',
    max_mos: 'Max MOS',
    threshold_mos: 'Threshold MOS',
    max_orders_per_period: 'Max orders per period',
    requisitions: 'Requisition(s)',
    details: 'Details',
    general: 'general',
    order: 'order',
    not_applicable: 'Not applicable',
  },
  fr: {
    select_a_program: 'Select a program',
    select_a_supplier: 'Select a supplier',
    select_an_order_type: 'Select an order type',
    select_a_period: 'Select a period',
    no_programs: 'No programs available',
    no_suppliers: 'No suppliers available',
    no_order_types: 'No order types available',
    no_periods: 'No periods available',
    program: 'programme',
    supplier: 'supplier',
    order_type: 'order type',
    period: 'period',
    max_mos: 'Max MOS',
    threshold_mos: 'Threshold MOS',
    max_orders_per_period: 'Max orders per period',
    requisitions: 'Requisition(s)',
    details: 'Details',
    general: 'General',
    order: 'order',
    not_applicable: 'Not applicable',
  },
  gil: {
    select_a_program: 'Select a program',
    select_a_supplier: 'Select a supplier',
    select_an_order_type: 'Select an order type',
    select_a_period: 'Select a period',
    no_programs: 'No programs available',
    no_suppliers: 'No suppliers available',
    no_order_types: 'No order types available',
    no_periods: 'No periods available',
    program: 'program',
    supplier: 'supplier',
    order_type: 'order type',
    period: 'period',
    max_mos: 'Max MOS',
    threshold_mos: 'Threshold MOS',
    max_orders_per_period: 'Max orders per period',
    requisitions: 'Requisition(s)',
    details: 'Details',
    general: 'General',
    order: 'order',
    not_applicable: 'Not applicable',
  },
  tl: {
    select_a_program: 'Select a program',
    select_a_supplier: 'Select a supplier',
    select_an_order_type: 'Select an order type',
    select_a_period: 'Select a period',
    no_programs: 'No programs available',
    no_suppliers: 'No suppliers available',
    no_order_types: 'No order types available',
    no_periods: 'No periods available',
    program: 'program',
    supplier: 'supplier',
    order_type: 'order type',
    period: 'period',
    max_mos: 'Max MOS',
    threshold_mos: 'Threshold MOS',
    max_orders_per_period: 'Max orders per period',
    requisitions: 'Requisition(s)',
    details: 'Details',
    general: 'General',
    order: 'order',
    not_applicable: 'Not applicable',
  },
  la: {
    select_a_program: 'Select a program',
    select_a_supplier: 'Select a supplier',
    select_an_order_type: 'Select an order type',
    select_a_period: 'Select a period',
    no_programs: 'No programs available',
    no_suppliers: 'No suppliers available',
    no_order_types: 'No order types available',
    no_periods: 'No periods available',
    program: 'program',
    supplier: 'supplier',
    order_type: 'order type',
    period: 'period',
    max_mos: 'Max MOS',
    threshold_mos: 'Threshold MOS',
    max_orders_per_period: 'Max orders per period',
    requisitions: 'Requisition(s)',
    details: 'Details',
    general: 'General',
    order: 'order',
    not_applicable: 'Not applicable',
  },
});

export default programStrings;
