/**
 * mSupply Mobile
 * Sustainable Solutions (NZ) Ltd. 2016
 */

import LocalizedStrings from 'react-native-localization';

export const tableStrings = new LocalizedStrings({
  gb: {
    actual_quantity: 'ACTUAL\nQUANTITY',
    available_stock: 'AVAILABLE STOCK',
    batch_expiry: 'EXPIRY',
    batch_cost_price: 'COST PRICE',
    batch_name: 'BATCH',
    category: 'Category',
    code: 'CODE',
    comment: 'COMMENT',
    created_date: 'CREATED DATE',
    current_stock: 'CURRENT STOCK',
    customer: 'CUSTOMER',
    delete: 'DELETE',
    department: 'Department',
    difference: 'DIFFERENCE',
    earliest_expiry: 'Earliest expiry',
    entered_date: 'ENTERED DATE',
    finalised: 'Finalised',
    id: 'ID',
    in_progress: 'In Progress',
    invoice_number: 'INVOICE\nNUMBER',
    invoices: 'INVOICES',
    item_code: 'ITEM CODE',
    item_name: 'ITEM NAME',
    items: 'ITEMS',
    monthly_usage: 'MONTHLY USE',
    name: 'NAME',
    no_change: 'No change',
    number_of_batches: 'Number of batches',
    number_received: 'NUMBER RECEIVED',
    number_sent: 'NUMBER SENT',
    pack_size: 'PACK SIZE',
    quantity: 'QUANTITY',
    remove: 'REMOVE',
    required_quantity: 'REQUESTED QTY',
    requisition_number: 'REQUISITION NUMBER',
    selected: 'SELECTED',
    snapshot_quantity: 'SNAPSHOT\nQUANTITY',
    status: 'STATUS',
    stock_on_hand: 'STOCK ON HAND',
    suggested_quantity: 'SUGGESTED QTY',
  },
  gil: {
    // TODO add: batch_expiry, batch_cost_price, batch_name, pack_size
    actual_quantity: 'Iraua\nMwaitina',
    available_stock: 'Mwaitin ae\niai ngkai',
    category: 'Kurubu',
    code: 'CODE',
    comment: 'Iai riki?',
    created_date: 'Bong -  karaoaia iai',
    current_stock: 'Mwaitin ae\niai ngkai',
    customer: 'Kiriniki/Aran te aoraki',
    delete: 'DELETE',
    department: 'Tabo',
    difference: 'Kaokorona',
    earliest_expiry: 'Earliest expiry',
    entered_date: 'Bong - karinaki iai',
    finalised: 'Finalised ',
    id: 'ID',
    in_progress: 'Ae karaoaki',
    invoice_number: 'INVOICE\nNUMBER',
    invoices: 'INVOICES',
    item_code: 'Ana code',
    item_name: 'Arana ',
    items: 'ITEMS',
    monthly_usage: 'MONTHLY USE',
    name: 'Arana',
    no_change: 'Akea te bitaki',
    number_of_batches: 'Mwatin taian batch',
    number_received: 'Mwaitin ae reke raoi',
    number_sent: 'Mwaitin ae kanakoaki',
    quantity: 'Mwaitina',
    remove: 'REMOVE',
    required_quantity: 'Te Mwaiti\nae tangiraki',
    requisition_number: 'REQUISITION NUMBER',
    selected: 'Rineaki',
    snapshot_quantity: 'Te mwaiti',
    status: 'Teina\nngkai',
    stock_on_hand: 'Mwaitin ae\niai ngkai',
    suggested_quantity: 'Mwaiti ae\nkaantaningaki',
  },
  tl: {
    actual_quantity: 'Qtd. Hasai',
    available_stock: 'Qtd. Disponivel',
    batch_expiry: 'PRAZU SASAN',
    batch_cost_price: 'KUSTU PRESU',
    batch_name: 'NUMERU-BATCH',
    category: 'Kategoria',
    code: 'KODIGU',
    comment: 'KOMENTÁRIU',
    created_date: 'DATA KRIA',
    current_stock: 'SASÁN ATUÁL',
    customer: 'KLIENTE',
    delete: 'APAGA',
    department: 'Departementu',
    difference: 'DIFERENSA',
    earliest_expiry: 'Data Prazu besik liu',
    entered_date: 'Data Hatama',
    finalised: 'Finaliza tiha ona',
    id: 'ID',
    in_progress: 'Progresu Hela',
    invoice_number: 'NUMERU INVOICE',
    invoices: 'INVOICES',
    item_code: 'KODIGU SASAN',
    item_name: 'NARAN ITEM',
    items: 'ITEMS',
    monthly_usage: 'KONSUMU MENSAL',
    name: 'NARAN',
    no_change: "Prense iha ne'e",
    number_of_batches: 'Numeru-Batch',
    number_received: 'Qtd. SIMU',
    number_sent: 'Qtd. HARUKA MAI',
    pack_size: 'PAKOTE SASUKAT',
    quantity: 'KUANTIDADE',
    remove: 'HASAI',
    required_quantity: 'Qtd. HUSU/EZIJE',
    requisition_number: 'NÚMERU REKUIZISAUN',
    selected: 'SELESIONA',
    snapshot_quantity: 'Qtd. IHA ARMAZEN',
    status: 'ESTATUS',
    stock_on_hand: 'Qtd. IHA ARMAZEN',
    suggested_quantity: 'Qtd. SUJERE',
  },
});
