/**
 * mSupply Mobile
 * Sustainable Solutions (NZ) Ltd. 2016
 */

import LocalizedStrings from 'react-native-localization';

export const tableStrings = new LocalizedStrings({
  gb: {
    actual_quantity: 'ACTUAL\nQUANTITY',
    available_stock: 'AVAILABLE STOCK',
    batch_expiry: 'EXPIRY',
    batch_cost_price: 'COST PRICE',
    batch_name: 'BATCH',
    category: 'Category',
    code: 'CODE',
    comment: 'COMMENT',
    created_date: 'CREATED DATE',
    current_stock: 'CURRENT STOCK',
    customer: 'CUSTOMER',
    delete: 'DELETE',
    department: 'Department',
    difference: 'DIFFERENCE',
    earliest_expiry: 'Earliest expiry',
    entered_date: 'ENTERED DATE',
    finalised: 'Finalised',
    id: 'ID',
    in_progress: 'In Progress',
    invoice_number: 'INVOICE\nNUMBER',
    invoices: 'INVOICES',
    item_code: 'ITEM CODE',
    item_name: 'ITEM NAME',
    items: 'ITEMS',
    monthly_usage: 'MONTHLY\nUSE',
    name: 'NAME',
    no_change: 'No change',
    number_of_batches: 'Number of batches',
    number_received: 'NUMBER RECEIVED',
    number_sent: 'NUMBER SENT',
    our_stock: 'OUR\nSTOCK',
    pack_size: 'PACK SIZE',
    quantity: 'QUANTITY',
    remove: 'REMOVE',
    required_quantity: 'REQUESTED\nQUANTITY',
    requisition_number: 'REQUISITION NUMBER',
    selected: 'SELECTED',
    snapshot_quantity: 'SNAPSHOT\nQUANTITY',
    status: 'STATUS',
    stock_on_hand: 'STOCK ON HAND',
    supplier: 'SUPPLIER',
    suggested_quantity: 'SUGGESTED\nQUANTITY',
    supply_quantity: 'SUPPLY THIS\nINVOICE',
    their_stock: 'THEIR\nSTOCK',
  },
  gil: { // TODO add: batch_expiry, batch_cost_price, batch_name, pack_size, our_stock, supply_quantity, supplier
    actual_quantity: 'Iraua\nMwaitina',
    available_stock: 'Mwaitin ae\niai ngkai',
    category: 'Kurubu',
    code: 'CODE',
    comment: 'Iai riki?',
    created_date: 'Bong -  karaoaia iai',
    current_stock: 'Mwaitin ae\niai ngkai',
    customer: 'Kiriniki/Aran te aoraki',
    delete: 'DELETE',
    department: 'Tabo',
    difference: 'Kaokorona',
    earliest_expiry: 'Earliest expiry',
    entered_date: 'Bong - karinaki iai',
    finalised: 'Finalised ',
    id: 'ID',
    in_progress: 'Ae karaoaki',
    invoice_number: 'INVOICE\nNUMBER',
    invoices: 'INVOICES',
    item_code: 'Ana code',
    item_name: 'Arana ',
    items: 'ITEMS',
    monthly_usage: 'MONTHLY USE',
    name: 'Arana',
    no_change: 'Akea te bitaki',
    number_of_batches: 'Mwatin taian batch',
    number_received: 'Mwaitin ae reke raoi',
    number_sent: 'Mwaitin ae kanakoaki',
    quantity: 'Mwaitina',
    remove: 'REMOVE',
    required_quantity: 'Te Mwaiti\nae tangiraki',
    requisition_number: 'REQUISITION NUMBER',
    selected: 'Rineaki',
    snapshot_quantity: 'Te mwaiti',
    status: 'Teina\nngkai',
    stock_on_hand: 'Mwaitin ae\niai ngkai',
    suggested_quantity: 'Mwaiti ae\nkaantaningaki',
  },
  tl: { // TODO add: batch_expiry, batch_cost_price, batch_name, pack_size, our_stock, supply_quantity, supplier
    actual_quantity: 'ATUÁL\nKUANTIDADE',
    available_stock: 'SASÁN DISPONIVEL',
    category: 'Kategoria',
    code: 'KODIGU',
    comment: 'KOMENTÁRIU',
    created_date: 'DADUS KRIA',
    current_stock: 'SASÁN ATUÁL',
    customer: 'KLIENTE',
    delete: 'HAPUS',
    department: 'Departementu',
    difference: 'DIFERENSA',
    earliest_expiry: "Dadus presu ne'ebé besik liu",
    entered_date: "DADUS NE'EBÉ\nHATAMA",
    finalised: 'Finaliza tiha ona',
    id: 'ID',
    in_progress: "Hala'o hela",
    invoice_number: 'NÚMERU\nKONTA',
    invoices: 'KONTA SIRA',
    item_code: 'SASÁN\nNIA KODIGU',
    item_name: 'SASÁN NIA NARAN',
    items: 'SASÁN SIRA',
    monthly_usage: 'UZA\nFULAN-FULAN',
    name: 'NARAN',
    no_change: 'La selu',
    number_of_batches: 'Sasán lubun hira',
    number_received: 'NÚMERU HIRA MAK SIMU',
    number_sent: 'NÚMERU HIRA MAK HARUKA',
    quantity: 'KUANTIDADE',
    remove: 'HASAI',
    required_quantity: "KUANTIDADE\nNE'EBÉ EZIJE",
    requisition_number: 'NÚMERU REKUIZISAUN',
    selected: 'SELESIONA',
    snapshot_quantity: 'KUANTIDADE TUIR\nDADUS PROGRAMA',
    status: 'ESTATUS',
    stock_on_hand: "SASÁN NE'EBÉ\nIHA HELA",
    suggested_quantity: "KUANTIDADE\nNE'EBÉ SUJERE",
  },
});
