/**
 * mSupply Mobile
 * Sustainable Solutions (NZ) Ltd. 2019
 */

import LocalizedStrings from 'react-native-localization';

export const tableStrings = new LocalizedStrings({
  gb: {
    actual_quantity: 'ACTUAL\nQUANTITY',
    available_stock: 'AVAILABLE STOCK',
    batch_expiry: 'EXPIRY',
    batch: 'Batch',
    category: 'Category',
    code: 'CODE',
    comment: 'COMMENT',
    created_date: 'CREATED DATE',
    current_stock: 'CURRENT STOCK',
    customer: 'CUSTOMER',
    delete: 'DELETE',
    department: 'Department',
    difference: 'DIFFERENCE',
    earliest_expiry: 'Earliest expiry',
    entered_date: 'ENTERED DATE',
    finalised: 'Finalised',
    id: 'ID',
    in_progress: 'In Progress',
    invoice_number: 'INVOICE\nNUMBER',
    invoices: 'INVOICES',
    item_code: 'ITEM CODE',
    item_name: 'ITEM NAME',
    items: 'ITEMS',
    monthly_usage: 'MONTHLY\nUSE',
    name: 'NAME',
    no_batch_name: 'no batch name',
    not_counted: 'Not Counted',
    number_of_batches: 'Number of batches',
    number_received: 'NUMBER RECEIVED',
    number_sent: 'NUMBER SENT',
    our_stock: 'OUR\nSTOCK',
    quantity: 'QUANTITY',
    remove: 'REMOVE',
    required_quantity: 'REQUESTED\nQUANTITY',
    requisition_number: 'REQUISITION NUMBER',
    selected: 'SELECTED',
    snapshot_quantity: 'SNAPSHOT\nQUANTITY',
    status: 'STATUS',
    stock_on_hand: 'STOCK ON HAND',
    supplier: 'SUPPLIER',
    suggested_quantity: 'SUGGESTED\nQUANTITY',
    supply_quantity: 'SUPPLY THIS\nINVOICE',
    their_stock: 'THEIR\nSTOCK',
  },
  fr: {
    actual_quantity: 'Quantité\nRéelle',
    available_stock: 'Quantité\ndisponible',
    batch_expiry: 'Expiration',
    batch: 'Lot',
    category: 'Catégorie',
    code: 'CODE',
    comment: 'COMMENTAIRE',
    created_date: 'DATE CRÉEE',
    current_stock: 'STOCK ACTUEL',
    customer: 'CLIENT',
    delete: 'SUPPRIMER',
    department: 'Départment',
    difference: 'Différence',
    earliest_expiry: "Date d'exipration la plus proche",
    entered_date: "Date d'entrée",
    finalised: 'Finalisé',
    id: 'ID',
    in_progress: 'En cours',
    invoice_number: 'NUMÉRO DE\nFACTURES',
    invoices: 'FACTURES',
    item_code: "Code de l'article",
    item_name: "Nom de l'article",
    items: 'Articles',
    monthly_usage: 'USAGE\nMENSUEL',
    name: 'NOM',
    no_batch_name: 'Pas de nom de lot',
    not_counted: 'Pas compté',
    number_of_batches: 'Nombre de lots',
    number_received: 'NUMÉRO REÇU',
    number_sent: 'NUMÉRO ENVOYÉ',
    our_stock: 'Notre\nStock',
    quantity: 'Quantité',
    remove: 'Enlever',
    required_quantity: 'QUANTITÉ\nDEMANDÉE',
    requisition_number: 'NUMÉRO DE\nRÉQUISITION',
    selected: 'Sélectionné',
    snapshot_quantity: 'instantané de\nla quantité',
    status: 'Statut',
    stock_on_hand: 'Stock disponible',
    supplier: 'Fournisseur',
    suggested_quantity: 'QUANTITÉ\nSUGGÉRÉE',
    supply_quantity: 'Fournir les\nquantités de\ncette facture',
    their_stock: 'Leur\nstock',
  },
  gil: {
    // TODO add: batch, no_batch_name
    // TODO re-translate: not_counted
    actual_quantity: 'IRAUA\nMWAITINA',
    available_stock: 'MWAITIN AE\nIAI NGKAI',
    batch_expiry: 'BANEN TAINA',
    category: 'Kurubu',
    code: 'CODE',
    comment: 'IAI RIKI?',
    created_date: 'BONG -\nKARAOAIA IAI',
    current_stock: 'MWAITIN AE\nIAI NGKAI',
    customer: 'KIRINIKI/ARAN TE AORAKI',
    delete: 'DELETE',
    department: 'Tabo',
    difference: 'KAOKORONA',
    earliest_expiry: 'Earliest expiry',
    entered_date: 'BONG -\nKARINAKI IAI',
    finalised: 'Finalised ',
    id: 'ID',
    in_progress: 'Ae karaoaki',
    invoice_number: 'INVOICE\nNUMBER',
    invoices: 'INVOICES',
    item_code: 'ANA CODE',
    item_name: 'ARANA ',
    items: 'ITEMS',
    monthly_usage: 'MONTHLY USE',
    name: 'ARANA',
    not_counted: 'Akea te bitaki',
    number_of_batches: 'Mwatin taian batch',
    number_received: 'MWAITIN AE REKE RAOI',
    number_sent: 'MWAITIN AE KANAKOAKI',
    our_stock: 'MAITIN ARA BWAIN AORAKI INANON BAIRA',
    quantity: 'MWAITINA',
    remove: 'REMOVE',
    required_quantity: 'TE MWAITI\nAE TANGIRAKI',
    requisition_number: 'REQUISITION NUMBER',
    selected: 'RINEAKI',
    snapshot_quantity: 'TE MWAITI',
    status: 'TEINA\nNGKAI',
    stock_on_hand: 'MWAITIN AE\nIAI NGKAI',
    suggested_quantity: 'MWAITI AE\nKAANTANINGAKI',
    supplier: 'KAMBANA NI KAOBWAI, PHARMACY',
    supply_quantity: 'BEEBA N OOTA MAN TE PHARMACY',
    their_stock: 'AIA BWAI\nN AORAKI',
  },
  tl: {
    // TODO add: batch, no_batch_name
    // TODO re-translate: not_counted
    actual_quantity: 'ATUÁL\nKUANTIDADE',
    available_stock: 'SASÁN DISPONIVEL',
    batch_expiry: 'PRAZU SASAN',
    category: 'Kategoria',
    code: 'KODIGU',
    comment: 'KOMENTÁRIU',
    created_date: 'DATA KRIA',
    current_stock: 'SASÁN ATUÁL',
    customer: 'KLIENTE',
    delete: 'APAGA',
    department: 'Departementu',
    difference: 'DIFERENSA',
    earliest_expiry: 'Data Prazu besik liu',
    entered_date: 'Data Hatama',
    finalised: 'Finaliza\ntiha ona',
    id: 'ID',
    in_progress: 'Progresu\nHela',
    invoice_number: 'NUMERU\nINVOICE',
    invoices: 'INVOICES',
    item_code: 'KODIGU SASAN',
    item_name: 'NARAN ITEM',
    items: 'ITEMS',
    monthly_usage: 'KONSUMU\nMENSAL',
    name: 'NARAN',
    not_counted: "Prense iha ne'e",
    number_of_batches: 'Numeru-Batch',
    number_received: 'Qtd. SIMU',
    number_sent: 'Qtd. HARUKA MAI',
    our_stock: 'ITA NIA\nSTOCK',
    quantity: 'KUANTIDADE',
    remove: 'HASAI',
    required_quantity: 'QTD.\nHUSU/EZIJE',
    requisition_number: 'NÚMERU REKUIZISAUN',
    selected: 'SELESIONA',
    snapshot_quantity: 'QTD. IHA\nARMAZEN',
    status: 'ESTATUS',
    stock_on_hand: 'QTD. IHA\nARMAZEN',
    suggested_quantity: 'QTD.\nSUJERE',
    supplier: 'Distribuidor',
    supply_quantity: 'KUANTIDADE\nDISTRIBUI',
    their_stock: 'SIRA NIA\nSTOCK',
  },
});

export default tableStrings;
